name: women_lose_weight_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

# Flutter Version :- 3.3.8
# Code Structure :- GetX

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_database: ^10.0.9
  firebase_storage: ^11.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  get: ^4.6.5
  sizer: ^2.0.15
  get_storage: ^2.0.3
  fluttertoast: ^8.1.1
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  scrollable_positioned_list: ^0.3.5
  syncfusion_flutter_gauges: ^20.3.57
  charts_flutter: ^0.12.0
  align_positioned: ^3.0.0
  date_picker_timeline: ^1.2.3
  flutter_slidable: ^2.0.0
  youtube_player_flutter: ^8.1.1
  table_calendar: ^3.0.8
  sqflite: ^2.0.0
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.0.5
  pin_code_fields: ^7.4.0
  flutter_rounded_date_picker: ^3.0.2
  flutter_local_notifications: ^12.0.3+1
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.7
  flutter_tts: ^3.6.1
  audioplayers: ^0.20.1
  share_plus: ^6.3.0
  url_launcher: ^6.1.6
  open_settings: ^2.0.2
  android_intent_plus: ^3.1.5
  rate_my_app: ^1.1.3
  date_format: ^2.0.7
  connectivity_plus: ^2.3.9
  in_app_purchase: ^3.0.8
  dio: ^4.0.6
  google_mobile_ads: ^2.3.0
  app_tracking_transparency: ^2.0.3
  image_picker: ^0.8.6

flutter:

  uses-material-design: true

  assets:
    - assets/database/
    - assets/icons/
    - assets/images/
    - assets/img_ex/
    - assets/img_ex/ABDOMINALCRUNCHES/
    - assets/img_ex/ADDUCTORSTRETCHINSTANDING/
    - assets/img_ex/AIRCYCLING/
    - assets/img_ex/ALTERNATINGHOOKS/
    - assets/img_ex/ALTVUP/
    - assets/img_ex/ANTERIORSHOULDERSTRETCH/
    - assets/img_ex/ARMCIRCLESCLOCKWISE/
    - assets/img_ex/ARMSCISSORS/
    - assets/img_ex/BACKBOWPULLS/
    - assets/img_ex/BACKWARDLUNGE/
    - assets/img_ex/BACKWARDLUNGEWITHFRONTKICKLEFT/
    - assets/img_ex/BACKWARDLUNGEWITHFRONTKICKRIGHT/
    - assets/img_ex/BENCHGLUTEKICKBACKLEFT/
    - assets/img_ex/BENCHGLUTEKICKBACKRIGHT/
    - assets/img_ex/BENTLEGTWIST/
    - assets/img_ex/BENTOVERROW/
    - assets/img_ex/BICYCLECRUNCHES/
    - assets/img_ex/BIRDDOG/
    - assets/img_ex/BODYSAW/
    - assets/img_ex/BOTTOMLEGLIFTLEFT/
    - assets/img_ex/BOTTOMLEGLIFTRIGHT/
    - assets/img_ex/BOXPUSHUPS/
    - assets/img_ex/BRIDGE/
    - assets/img_ex/BULGARIANSPLITSQUATLEFT/
    - assets/img_ex/BULGARIANSPLITSQUATRIGHT/
    - assets/img_ex/BURPEES/
    - assets/img_ex/BUTTBRIDGE/
    - assets/img_ex/BUTTKICKS/
    - assets/img_ex/CALFRAISEWITHSPLAYEDFOOT/
    - assets/img_ex/CALFSTRETCHLEFT/
    - assets/img_ex/CALFSTRETCHRIGHT/
    - assets/img_ex/CATCOWPOSE/
    - assets/img_ex/CHAIRBICYCLECRUNCH/
    - assets/img_ex/CHAIRSQUATS/
    - assets/img_ex/CHESTPRESSPULSE/
    - assets/img_ex/CHESTSTRETCH/
    - assets/img_ex/CHILDSPOSE/
    - assets/img_ex/CLAPPINGCRUNCHES/
    - assets/img_ex/CLASPHANDSBEHINDBACK/
    - assets/img_ex/CLOCKWISEARMSWINGS/
    - assets/img_ex/CLOCKWISESHOULDERROLLS/
    - assets/img_ex/COBRAS/
    - assets/img_ex/COBRASTRETCH/
    - assets/img_ex/CORRECTFOOTMOTION/
    - assets/img_ex/COUNTERCLOCKWISEARMSWINGS/
    - assets/img_ex/CRABKICKS/
    - assets/img_ex/CRABKICKUP/
    - assets/img_ex/CRABWALK/
    - assets/img_ex/CROSSARMCRUNCHES/
    - assets/img_ex/CROSSKNEEPLANK/
    - assets/img_ex/CROSSLEGSIDEBENDLEFT/
    - assets/img_ex/CROSSLEGSIDEBENDRIGHT/
    - assets/img_ex/CROSSTOUCHANDREACH/
    - assets/img_ex/CRUNCHKICKS/
    - assets/img_ex/CURTSYLUNGES/
    - assets/img_ex/DEADBUG/
    - assets/img_ex/DIAGONALPLANK/
    - assets/img_ex/DONKEYKICKSLEFT/
    - assets/img_ex/DONKEYKICKSRIGHT/
    - assets/img_ex/DOUBLEKNEESTOCHEST/
    - assets/img_ex/DOWNWARDFACINGDOG/
    - assets/img_ex/DOWNWARDFACINGDOGONTHEWALL/
    - assets/img_ex/DUMBBELLCHESTFLY/
    - assets/img_ex/DYNAMICCHEST/
    - assets/img_ex/ELBOWSBACK/
    - assets/img_ex/FASTSPIDERLUNGES/
    - assets/img_ex/FIREHYDRANTLEFT/
    - assets/img_ex/FIREHYDRANTRIGHT/
    - assets/img_ex/FLOORYRAISES/
    - assets/img_ex/FLUTTERKICKS/
    - assets/img_ex/FORWARDBEND/
    - assets/img_ex/FROGGYGLUTELIFTS/
    - assets/img_ex/FROGPRESS/
    - assets/img_ex/GLUTEKICKBACKCROSSOVERWITHLEFTLEG/
    - assets/img_ex/GLUTEKICKBACKCROSSOVERWITHRIGHTLEG/
    - assets/img_ex/GLUTESTRETCHLEFT/
    - assets/img_ex/GLUTESTRETCHRIGHT/
    - assets/img_ex/HAMSTRINGSTRETCHWITHFOAMROLLER/
    - assets/img_ex/HAVYKRAISES/
    - assets/img_ex/HEELSTOTHEHEAVENS/
    - assets/img_ex/HEELTOUCH/
    - assets/img_ex/HIGHSTEPPING/
    - assets/img_ex/HIPBRIDGELEGLIFTLEFT/
    - assets/img_ex/HIPBRIDGELEGLIFTRIGHT/
    - assets/img_ex/INCHWORMS/
    - assets/img_ex/INCLINEPUSHUPS/
    - assets/img_ex/INOUTS/
    - assets/img_ex/ITBANDSTRETCHWITHFOAMROLLERLEFT/
    - assets/img_ex/ITBANDSTRETCHWITHFOAMROLLERRIGHT/
    - assets/img_ex/JUMPINGJACKS/
    - assets/img_ex/JUMPINGSQUATS/
    - assets/img_ex/KNEELIFTLEFT/
    - assets/img_ex/KNEELIFTRIGHT/
    - assets/img_ex/KNEELINGLUNGESTRETCHLEFT/
    - assets/img_ex/KNEELINGLUNGESTRETCHRIGHT/
    - assets/img_ex/KNEELINGSIDEPLANKLEFT/
    - assets/img_ex/KNEELINGSIDEPLANKRIGHT/
    - assets/img_ex/KNEEPUSHUPS/
    - assets/img_ex/KNEETOCHESTSTRETCHLEFT/
    - assets/img_ex/KNEETOCHESTSTRETCHRIGHT/
    - assets/img_ex/KNEETOELBOWCRUNCHES/
    - assets/img_ex/LATERALPLANKWALK/
    - assets/img_ex/LEFTLEGLATERALRAISE/
    - assets/img_ex/LEFTLUNGEKNEEHOPS/
    - assets/img_ex/LEFTQUADSTRETCHWITHWALL/
    - assets/img_ex/LEFTSIDELYINGFORWARDLEGLIFT/
    - assets/img_ex/LEGRAISES/
    - assets/img_ex/LEGSPREADS/
    - assets/img_ex/LEGSUPTHEWALL/
    - assets/img_ex/LEVATORSCAPULAESTRETCHLEFT/
    - assets/img_ex/LEVATORSCAPULAESTRETCHRIGHT/
    - assets/img_ex/LONGARMCRUNCHES/
    - assets/img_ex/LUNGES/
    - assets/img_ex/LYINGBUTTERFLYSTRETCH/
    - assets/img_ex/LYINGTWISTSTRETCHLEFT/
    - assets/img_ex/LYINGTWISTSTRETCHRIGHT/
    - assets/img_ex/MODIFIEDBURPEES/
    - assets/img_ex/MOUNTAINCLIMBER/
    - assets/img_ex/MOUNTAINCLIMBERSQUATTHRUST/
    - assets/img_ex/OBLIQUECROSSOVERCRUNCHLEFT/
    - assets/img_ex/OBLIQUECROSSOVERCRUNCHRIGHT/
    - assets/img_ex/ONEDOWNTWOUPS/
    - assets/img_ex/OPENCHAINKNEEEXTENSIONLEFT/
    - assets/img_ex/OPENCHAINKNEEEXTENSIONRIGHT/
    - assets/img_ex/OVERHEADARMCLOCKWISECIRCLES/
    - assets/img_ex/OVERHEADARMCOUNTERCLOCKWISECIRCLES/
    - assets/img_ex/PENDULUMSWINGS/
    - assets/img_ex/PIGEONPOSELEFT/
    - assets/img_ex/PIGEONPOSERIGHT/
    - assets/img_ex/PILATESCLAMSHELLLEFT/
    - assets/img_ex/PILATESCLAMSHELLRIGHT/
    - assets/img_ex/PLANK/
    - assets/img_ex/PLANKANDREACH/
    - assets/img_ex/PLANKHIPDIPS/
    - assets/img_ex/PLANKJACKS/
    - assets/img_ex/PLANKLEGUP/
    - assets/img_ex/PLANKTAPS/
    - assets/img_ex/PLIESQUATS/
    - assets/img_ex/PRONEFLUTTERKICKS/
    - assets/img_ex/PUNCHES/
    - assets/img_ex/PUSHUPROTATION/
    - assets/img_ex/PUSHUPS/
    - assets/img_ex/QUADSTRETCH/
    - assets/img_ex/QUADSTRETCHWITHFOAMROLLER/
    - assets/img_ex/QUARTERWALLSQUAT/
    - assets/img_ex/QUICKFEET/
    - assets/img_ex/RECLINEDOBLIQUETWIST/
    - assets/img_ex/REVERSECRUNCHES/
    - assets/img_ex/REVERSECRUNCHESWITHLEGRAISED/
    - assets/img_ex/RIGHTLEGLATERALRAISE/
    - assets/img_ex/RIGHTLUNGEKNEEHOPS/
    - assets/img_ex/RIGHTQUADSTRETCHWITHWALL/
    - assets/img_ex/RIGHTSIDELYINGFORWARDLEGLIFT/
    - assets/img_ex/ROUNDHOUSESQUATKICKS/
    - assets/img_ex/RUSSIANTWIST/
    - assets/img_ex/SCISSORS/
    - assets/img_ex/SEATEDABSCLOCKWISECIRCLES/
    - assets/img_ex/SEATEDABSCOUNTERCLOCKWISECIRCLES/
    - assets/img_ex/SEATEDBUTTERFLYSTRETCH/
    - assets/img_ex/SEATEDHAMSTRINGSTRETCHLEFT/
    - assets/img_ex/SEATEDHAMSTRINGSTRETCHRIGHT/
    - assets/img_ex/SEATEDINOUTS/
    - assets/img_ex/SEATEDSIDEBENDLEFT/
    - assets/img_ex/SEATEDSIDEBENDRIGHT/
    - assets/img_ex/SEATEDSPINALTWISTLEFT/
    - assets/img_ex/SEATEDSPINALTWISTRIGHT/
    - assets/img_ex/SHORTARCQUADLEFT/
    - assets/img_ex/SHORTARCQUADRIGHT/
    - assets/img_ex/SHOULDERSTRETCH/
    - assets/img_ex/SHOULDERSTRETCHWITHCHAIR/
    - assets/img_ex/SIDEBENDREACHLEFT/
    - assets/img_ex/SIDEBENDREACHRIGHT/
    - assets/img_ex/SIDEBRIDGESLEFT/
    - assets/img_ex/SIDEBRIDGESRIGHT/
    - assets/img_ex/SIDECRUNCHESLEFT/
    - assets/img_ex/SIDECRUNCHESRIGHT/
    - assets/img_ex/SIDEHOP/
    - assets/img_ex/SIDELEGCIRCLESLEFT/
    - assets/img_ex/SIDELEGCIRCLESRIGHT/
    - assets/img_ex/SIDELEGRAISELEFT/
    - assets/img_ex/SIDELEGRAISERIGHT/
    - assets/img_ex/SIDELUNGES/
    - assets/img_ex/SIDELYINGKICKBACKLEFT/
    - assets/img_ex/SIDELYINGKICKBACKRIGHT/
    - assets/img_ex/SIDELYINGLEGLIFTLEFT/
    - assets/img_ex/SIDELYINGLEGLIFTRIGHT/
    - assets/img_ex/SIDENECKSTRETCHLEFT/
    - assets/img_ex/SIDENECKSTRETCHRIGHT/
    - assets/img_ex/SIDEPLANKFRONTKICKLEFT/
    - assets/img_ex/SIDEPLANKFRONTKICKRIGHT/
    - assets/img_ex/SIDEPLANKLEFT/
    - assets/img_ex/SIDEPLANKRIGHT/
    - assets/img_ex/SIDESTEPJACKS/
    - assets/img_ex/SINGLELEFTLEGCALFRAISES/
    - assets/img_ex/SINGLELEGHIPROTATION/
    - assets/img_ex/SINGLERIGHTLEGCALFRAISES/
    - assets/img_ex/SITTINGHAMSTRINGSTRETCHLEFT/
    - assets/img_ex/SITTINGHAMSTRINGSTRETCHRIGHT/
    - assets/img_ex/SITUPS/
    - assets/img_ex/SITUPTWIST/
    - assets/img_ex/SKATERJUMP/
    - assets/img_ex/SKIPPINGWITHOUTROPE/
    - assets/img_ex/SPINELUMBARTWISTSTRETCHLEFT/
    - assets/img_ex/SPINELUMBARTWISTSTRETCHRIGHT/
    - assets/img_ex/SPLITSQUATLEFT/
    - assets/img_ex/SPLITSQUATRIGHT/
    - assets/img_ex/SQUATJACKS/
    - assets/img_ex/SQUATPULSES/
    - assets/img_ex/SQUATREACHUPS/
    - assets/img_ex/SQUATS/
    - assets/img_ex/STANDINGBICEPSSTRETCHLEFT/
    - assets/img_ex/STANDINGBICEPSSTRETCHRIGHT/
    - assets/img_ex/STANDINGBICYCLECRUNCHES/
    - assets/img_ex/STANDINGHIPCIRCLE/
    - assets/img_ex/STANDINGOBLIQUECRUNCHESLEFT/
    - assets/img_ex/STANDINGOBLIQUECRUNCHESRIGHT/
    - assets/img_ex/STANDINGSIDEBEND/
    - assets/img_ex/STARJUMPS/
    - assets/img_ex/STEPUPONTOCHAIR/
    - assets/img_ex/STRAIGHTARMPLANK/
    - assets/img_ex/STRAIGHTLEGFIREHYDRANTLEFT/
    - assets/img_ex/STRAIGHTLEGFIREHYDRANTRIGHT/
    - assets/img_ex/STRAIGHTLEGRAISELEFT/
    - assets/img_ex/STRAIGHTLEGRAISERIGHT/
    - assets/img_ex/SUMOSQUAT/
    - assets/img_ex/SUPERMAN/
    - assets/img_ex/SUPINEHAMSTRINGSTRETCHLEFT/
    - assets/img_ex/SUPINEHAMSTRINGSTRETCHRIGHT/
    - assets/img_ex/SWIMMERANDSUPERMAN/
    - assets/img_ex/THENOGAP/
    - assets/img_ex/TOETAP/
    - assets/img_ex/TRICEPSDIPS/
    - assets/img_ex/TRICEPSKICKBACKS/
    - assets/img_ex/TRICEPSSTRETCHLEFT/
    - assets/img_ex/TRICEPSSTRETCHRIGHT/
    - assets/img_ex/TRUNKROTATION/
    - assets/img_ex/UPANDDOWNPLANK/
    - assets/img_ex/UPDOWNNODS/
    - assets/img_ex/VCRUNCH/
    - assets/img_ex/VHOLD/
    - assets/img_ex/WALLPUSHUPS/
    - assets/img_ex/WALLSIT/
    - assets/img_ex/XBURPEES/
    - assets/img_ex/XMANCRUNCH/
    - assets/raw/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/roboto-regular.ttf #Reguler
          weight: 400
        - asset: fonts/roboto-medium.ttf #Medium
          weight: 500
        - asset: fonts/roboto-bold.ttf #Bold
          weight: 600